import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Nex App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
                <h1 className="font-extrabold text-center text-7xl">
                    <span className="text-blue-500">Boilerplate</span> FE
                </h1>
            </div>
        </>
    )
}

export default Home
